### ISSUE TITLE
SCSS source file missing

### ISSUE THREAD

**Issue by ptitbob** [cowboysmall-tools/hugo-dev-resume-theme#1]
Hello,

Contrary to that you write in hugo theme description, the SCSS source is missing. Could you make them available (in asset repository in the root of theme ?

;) have fun

**Comment by cowboysmall** [comment]
Oops! Sorry about that.

I've added the SCSS source to assets and pushed it. I have not set up the theme to use SCSS though - because it requires the extended version of Hugo - but I will definitely do it at a later date.

Thanks,

J.K.

**Comment by cowboysmall** [comment]
I added the SCSS files to the wrong location - I have resolved this with the last commit - also I added support for CSS generation from the SCSS through Hugo Pipes (extended Hugo required of course).

Thanks,

J.K.
