### ISSUE TITLE
assets/images/

### ISSUE THREAD

**Issue by KHannibal** [cowboysmall-tools/hugo-dev-resume-theme#14]
https://github.com/cowboysmall-tools/hugo-devresume-theme/blob/ccd34cdca3b8316eaee6aaaad209ec002aa1d9af/layouts/partials/summary.html#L7

`assets/images/`

should be

`/assets/images/`

**Comment by cowboysmall** [comment]
Not necessarily.  

Look in the example site config.toml - I assume something in the following format:

```
# Page settings

baseURL = "http://example.org/"
languageCode = "en"
...
```

i.e. http://example.org/ with the trailing slash. This is a convention I have used across all of my themes. But I might change this.

Let me review and think about it, and I'll get back to you.

J.K.
