### ISSUE TITLE
building issue

### ISSUE THREAD

**Issue by jasminesolve** [cowboysmall-tools/hugo-dev-resume-theme#2]
hi,

When I use hugo to generate the website in public folder, the theme disappeared, only text content left. Before this step, everything goes well in http://localhost:1313/. Could you help with this issue? THX.

**Comment by jasminesolve** [comment]
I figure out the problem:
when hugo generate the website in public folder, the file index.html will be generated with some errors inside, especially in line<link ref='stylesheet'...>. Just let you know. The problem is solved.
Thank you.

**Comment by cowboysmall** [comment]
Hi,

just seeing this now. Can you look in your config.toml and check the baseurl setting, and change it to the following before you generate your website:

```
baseurl = "http://<mydomain.com>"
```

Hugo will generate the links for stylesheets, etc. based on this setting, so you will need to make sure it reflects your deployment. If you want to test it before deployment, chenge it as follows:

baseurl = "http://localhost:1313"

and regenerate. But remember to change it back before generating for deployment.

J.K.
