### ISSUE TITLE
theme-color-primary

### ISSUE THREAD

**Issue by jasminesolve** [cowboysmall-tools/hugo-dev-resume-theme#3]
Hi,

I found another issue about theme color changing:
even I changed the theme-color-primary in devresume.scss, the color still keep the same. 
Could you help with this issue?
THX.

**Comment by cowboysmall** [comment]
Sorry but currently the theme does not currently support SCSS - the SCSS files are included for completeness. 

But I'll look into adding support for CSS generation from the SCSS soon. Not now though - I'm in bed (it's almost 2 AM where I am :-) )

J.K.

**Comment by cowboysmall** [comment]
I've added support for processing SCSS through Hugo Pipes - you should be able to make your change in devresume.scss, and providing you have the extended Hugo installed, it should work for you.

Let me know if there are any issues. And I will let you close the issue.

J.K.

**Comment by cowboysmall** [comment]
I've added support for changing:

  * $theme-color-primary 
  * $theme-text-color-primary

within config.toml by changing the following params:

  * primary_color = "#54B689"
  * text_primary_color = "#292929"

J.K.

**Comment by jasminesolve** [comment]
It works. Thank you for your efforts!

**Comment by cowboysmall** [comment]
@jasminesolve - No problem. I've changed the names of the colour params from:

  * primary_color
  * text_primary_color

to 

  * primaryColor
  * textPrimaryColor

in the latest commit.

J.K.

**Comment by MHillier98** [comment]
Hey, Hugo newbie here!
I swear I must be crazy or something, but I'm trying to set those param variables in `config.yaml`, and nothing is changing.

```
    primaryColor = "#0074D9"
    textPrimaryColor = "#111111"
```

I did a Search/Replace for every instance of the default in VS Code, and that fixed it, but I assumed that those params would update the compiled version when the `hugo` command was run? Thanks!

**Comment by cowboysmall** [comment]
@MHillier98  - sorry for the late response. Can you check you are using the extended version of hugo? You can check by executing the following command:

```
hugo version -v
Hugo Static Site Generator v0.60.0-DEV/extended linux/amd64 BuildDate: unknown
```
If it's not the extended version, then that's likely your problem.

J.K.

**Comment by MHillier98** [comment]
Ah - didn't realise that was a requirement - I'll have to install that then, I guess.

Is it something that this theme requires? I guess it might be worth mentioning in the README?

**Comment by cowboysmall** [comment]
@MHillier98 - the fact the theme supports SASS / SCSS implies the Hugo extended version in order to take advantage of that feature - the theme will work without the extended version, but it will use the generated versions of the CSS, and you will not be able to take advantage of the SCSS / SASS features. 

The installation docs are pretty clear - https://gohugo.io/getting-started/installing/ - they recommend installing the extended version if support for SASS / SCSS is required.

**Comment by MHillier98** [comment]
Ok thanks - sorry for being a noob lol :)

**Comment by cowboysmall** [comment]
@MHillier98 - not at all! And I'm delighted you're using the theme :+1: 

One thing - if you discover any further issues feel free to open a new issue - this issue has been closed. Opening a new issue will result in a quicker response from me. Also, it allows me to better keep track of any changes I need / want to make.

Enjoy Hugo!

J.K.
