### ISSUE TITLE
TOCSS : failed to transform "scss/devresume.scss"

### ISSUE THREAD

**Issue by valderaplets** [cowboysmall-tools/hugo-dev-resume-theme#7]
Hello,

Currently the theme demo on the Hugo Themes website is broken.

I think i have the same issue than that guy : [issue hugothemes](https://github.com/gohugoio/hugoThemes/issues/814)

with :

- hugo 0.68.0

Step to reproduce : 

```
$ hugo server
Built in 6 ms
Error: Error building site: TOCSS: failed to transform "scss/devresume.scss" (text/x-scss): resource "scss/scss/devresume.scss_e6aa7b7a795a91be5e3855195558b0ad" not found in file cache
```

Quentin.

**Comment by cowboysmall** [comment]
Hi Quentin,

sorry for the late response - I've been a little distracted. I regenerated the resources and committed them - this should resolve the issue (if it hasn't already been resolved).

Thanks for letting me know.

J.K.

**Comment by valderaplets** [comment]
It's ok ! Thx !
